openapi: 3.0.1
info:
  title: 东方夜雀食堂wiki
  description: ''
  version: 1.0.0
tags: []
paths:
  /api/ingredients:
    get:
      summary: 获取所有食材
      deprecated: false
      description: ''
      tags: []
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  page:
                    type: integer
                  limit:
                    type: integer
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        image:
                          type: string
                        level:
                          type: integer
                        source:
                          type: string
                        category:
                          type: string
                        price:
                          type: integer
                        description:
                          type: string
                        tags:
                          type: array
                          items:
                            type: string
                required:
                  - total
                  - page
                  - limit
                  - data
                  - 01JPY04VHJ9ZFFV54R413BR2K8
          headers: {}
      security: []
  /api/ingredients/{id}:
    get:
      summary: 获取单个食材详情
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  image:
                    type: string
                  level:
                    type: integer
                  source:
                    type: string
                  category:
                    type: string
                  price:
                    type: integer
                  description:
                    type: string
                  tags:
                    type: array
                    items:
                      type: string
                required:
                  - id
                  - name
                  - image
                  - level
                  - source
                  - category
                  - price
                  - description
                  - tags
          headers: {}
      security: []
  /api/recipes:
    get:
      summary: 获取所有料理
      deprecated: false
      description: ''
      tags: []
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  page:
                    type: integer
                  limit:
                    type: integer
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        image:
                          type: string
                        level:
                          type: integer
                        source:
                          type: string
                        price:
                          type: integer
                        tool:
                          type: string
                        time:
                          type: string
                        description:
                          type: string
                        tags:
                          type: array
                          items:
                            type: string
                        ingredients:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              quantity:
                                type: string
                            required:
                              - name
                              - quantity
                        acquisition:
                          type: string
                required:
                  - total
                  - page
                  - limit
                  - data
          headers: {}
      security: []
  /api/recipes/{id}:
    get:
      summary: 获取单个料理详情
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  image:
                    type: string
                  level:
                    type: integer
                  source:
                    type: string
                  price:
                    type: integer
                  tool:
                    type: string
                  time:
                    type: string
                  description:
                    type: string
                  tags:
                    type: array
                    items:
                      type: string
                  ingredients:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        quantity:
                          type: string
                      required:
                        - name
                        - quantity
                  acquisition:
                    type: string
                required:
                  - id
                  - name
                  - image
                  - level
                  - source
                  - price
                  - tool
                  - time
                  - description
                  - tags
                  - ingredients
                  - acquisition
          headers: {}
      security: []
  /api/drinks:
    get:
      summary: 获取所有酒水
      deprecated: false
      description: ''
      tags: []
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  page:
                    type: integer
                  limit:
                    type: integer
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        image:
                          type: string
                        level:
                          type: integer
                        source:
                          type: string
                        category:
                          type: string
                        price:
                          type: integer
                        description:
                          type: string
                        tags:
                          type: array
                          items:
                            type: string
                required:
                  - total
                  - page
                  - limit
                  - data
          headers: {}
      security: []
  /api/drinks/{id}:
    get:
      summary: ' 获取单个酒水详情'
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  image:
                    type: string
                  level:
                    type: integer
                  source:
                    type: string
                  category:
                    type: string
                  price:
                    type: integer
                  description:
                    type: string
                  tags:
                    type: array
                    items:
                      type: string
                required:
                  - id
                  - name
                  - image
                  - level
                  - source
                  - category
                  - price
                  - description
                  - tags
          headers: {}
      security: []
  /api/customers:
    get:
      summary: 获取所有顾客
      deprecated: false
      description: ''
      tags: []
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  total:
                    type: integer
                  page:
                    type: integer
                  limit:
                    type: integer
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        type:
                          type: string
                        region:
                          type: string
                        budget:
                          type: integer
                        location:
                          type: array
                          items:
                            type: string
                        liked_recipe_tags:
                          type: array
                          items:
                            type: string
                        disliked_recipe_tags:
                          type: array
                          items:
                            type: string
                        liked_drink_tags:
                          type: array
                          items:
                            type: string
                required:
                  - total
                  - page
                  - limit
                  - data
          headers: {}
      security: []
  /api/customers/{id}:
    get:
      summary: 获取单个顾客详情
      deprecated: false
      description: ''
      tags: []
      parameters:
        - name: id
          in: path
          description: ''
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  type:
                    type: string
                  region:
                    type: string
                  budget:
                    type: integer
                  location:
                    type: array
                    items:
                      type: string
                  liked_recipe_tags:
                    type: array
                    items:
                      type: string
                  disliked_recipe_tags:
                    type: array
                    items:
                      type: string
                  liked_drink_tags:
                    type: array
                    items:
                      type: string
                required:
                  - id
                  - name
                  - type
                  - region
                  - budget
                  - location
                  - liked_recipe_tags
                  - disliked_recipe_tags
                  - liked_drink_tags
          headers: {}
      security: []
  /api/search:
    get:
      summary: 全局搜索
      deprecated: false
      description: ''
      tags: []
      parameters: []
      responses:
        '200':
          description: ''
          content:
            application/json:
              schema:
                type: object
                properties:
                  ingredients:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        description:
                          type: string
                  recipes:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        description:
                          type: string
                  drinks:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        description:
                          type: string
                  customers:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                        region:
                          type: string
                required:
                  - ingredients
                  - recipes
                  - drinks
                  - customers
          headers: {}
      security: []
components:
  schemas: {}
  securitySchemes: {}
servers: []
security: []
